import countryRepository from './country.repository';
import userRepository from './user.repository';
import industryRepository from './industry.repository';
import paymentRepository from './payment.repository';

export default {
  countryRepository,
  userRepository,
  industryRepository,
  paymentRepository,
  // accountRepository,
  // addressRepository,
  // mediaRepository,
  // settingRepository,
  // categoryRepository,
  // childCategoryRepository,
  // productVariantRepository,
  // subCategoryRepository,
  // cmsRepository,
  // discountRepository,
  // brandRepository,
  // generalSettingRepository,
  // productRepository,
  // userRepository,
  // contactUsRepository,
  // customNotificationsRepository,
  // productComplaintRepository,
  // notificationRepository,
  // faqRepository,
  // shippingLogRepository,
  // cartRepository,
  // paymentCardRepository,
  // storeRepository,
  // orderRepository,
  // earningRepository,
  // howItWorksRepository,
  // promotionRepository,
  // getEarlyAccessRepository,
  // bannerRepository,
  // productNotifyMeRepository,
};
